language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '13'
jobs:
  include:
    - stage: test
      script:
        - npm run test
    - stage: deploy
      if: branch = master
      script: npm run travis-deploy-once "npm run semantic-release"